sudo: required
dist: trusty
os: linux
language: generic
if: branch = master
cache:
  directories:
  - depends/built
  - depends/sdk-sources
  - "$HOME/.ccache"
env:
  global:
  - MAKEJOBS=-j3
  - RUN_TESTS=false
  - CHECK_DOC=0
  - BOOST_TEST_RANDOM=1$TRAVIS_BUILD_ID
  - CCACHE_SIZE=100M
  - CCACHE_TEMPDIR=/tmp/.ccache-temp
  - CCACHE_COMPRESS=1
  - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
  - SDK_URL=https://bitcoincore.org/depends-sources/sdks
  - PYTHON_DEBUG=1
  - WINEDEBUG=fixme-all
  - GARLICOIN_SCRYPT=0
  matrix:
  - HOST=arm-linux-gnueabihf PACKAGES="g++-arm-linux-gnueabihf" DEP_OPTS="NO_QT=1"
    CHECK_DOC=0 GOAL="install" BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports"
  - HOST=i686-w64-mingw32 DPKG_ADD_ARCH="i386" DEP_OPTS="NO_QT=1" PACKAGES="python3
    python3-dev python3-pip nsis g++-mingw-w64-i686 wine1.6 bc" GOAL="install" BITCOIN_CONFIG="--enable-reduce-exports"
    GARLICOIN_SCRYPT=1
  - HOST=i686-pc-linux-gnu PACKAGES="g++-multilib bc python3-zmq python3-dev python3-pip"
    DEP_OPTS="NO_QT=1" GOAL="install" BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat
    --enable-reduce-exports LDFLAGS=-static-libstdc++" USE_SHELL="/bin/dash" GARLICOIN_SCRYPT=1
  - HOST=x86_64-w64-mingw32 DPKG_ADD_ARCH="i386" DEP_OPTS="NO_QT=1" PACKAGES="python3
    python3-dev python3-pip nsis g++-mingw-w64-x86-64 wine1.6 bc" GOAL="install" BITCOIN_CONFIG="--enable-reduce-exports
    --enable-sse2" GARLICOIN_SCRYPT=1
  - HOST=x86_64-unknown-linux-gnu PACKAGES="python3-zmq python3-dev python3-pip qtbase5-dev
    qttools5-dev-tools protobuf-compiler libdbus-1-dev libharfbuzz-dev" DEP_OPTS="NO_QT=1
    NO_UPNP=1 DEBUG=1 ALLOW_HOST_PACKAGES=1" GOAL="install" BITCOIN_CONFIG="--enable-zmq
    --with-gui=qt5 --enable-glibc-back-compat --enable-reduce-exports --enable-sse2
    CPPFLAGS=-DDEBUG_LOCKORDER" GARLICOIN_SCRYPT=1
  - HOST=x86_64-unknown-linux-gnu PACKAGES="python3 python3-dev python3-pip" DEP_OPTS="NO_WALLET=1"
    GOAL="install" BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports
    --enable-sse2" GARLICOIN_SCRYPT=1
  - HOST=x86_64-apple-darwin11 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin
    libz-dev libbz2-dev libtiff-tools python-dev" BITCOIN_CONFIG="--enable-gui --enable-reduce-exports
    --enable-sse2" OSX_SDK=10.11 GOAL="deploy"
before_install:
- export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" |
  sed "s|::|:|g")
- export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/pyenv/d' | tr "\n" ":" | sed
  "s|::|:|g")
install:
- if [ -n "$DPKG_ADD_ARCH" ]; then sudo dpkg --add-architecture "$DPKG_ADD_ARCH" ;
  fi
- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get update; fi
- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends
  --no-upgrade -qq $PACKAGES; fi
before_script:
- if [ "$TRAVIS_EVENT_TYPE" = "pull_request" ]; then contrib/devtools/commit-script-check.sh
  $TRAVIS_COMMIT_RANGE; fi
- unset CC; unset CXX
- if [ "$CHECK_DOC" = 1 ]; then contrib/devtools/check-doc.py; fi
- mkdir -p depends/SDKs depends/sdk-sources
- if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
  curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz;
  fi
- if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
  tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
- make $MAKEJOBS -C depends HOST=$HOST $DEP_OPTS
script:
- if [ "$CHECK_DOC" = 1 -a "$TRAVIS_REPO_SLUG" = "garlicoin-project/garlicoin" -a
  "$TRAVIS_PULL_REQUEST" = "false" ]; then while read LINE; do travis_retry gpg --keyserver
  hkp://subset.pool.sks-keyservers.net --recv-keys $LINE; done < contrib/verify-commits/trusted-keys;
  fi
- if [ "$CHECK_DOC" = 1 -a "$TRAVIS_REPO_SLUG" = "garlicoin-project/garlicoin" -a
  "$TRAVIS_PULL_REQUEST" = "false" ]; then git fetch --unshallow; fi
- if [ "$CHECK_DOC" = 1 -a "$TRAVIS_REPO_SLUG" = "garlicoin-project/garlicoin" -a
  "$TRAVIS_PULL_REQUEST" = "false" ]; then contrib/verify-commits/verify-commits.sh;
  fi
- export TRAVIS_COMMIT_LOG=`git log --format=fuller -1`
- if [ -n "$USE_SHELL" ]; then export CONFIG_SHELL="$USE_SHELL"; fi
- OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
- BITCOIN_CONFIG_ALL="--disable-dependency-tracking --prefix=$TRAVIS_BUILD_DIR/depends/$HOST
  --bindir=$OUTDIR/bin --libdir=$OUTDIR/lib"
- depends/$HOST/native/bin/ccache --max-size=$CCACHE_SIZE
- test -n "$USE_SHELL" && eval '"$USE_SHELL" -c "./autogen.sh"' || ./autogen.sh
- mkdir build && cd build
- "../configure --cache-file=config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG || (
  cat config.log && false)"
- make distdir VERSION=$HOST
- cd garlicoin-$HOST
- "./configure --cache-file=../config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG ||
  ( cat config.log && false)"
- make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL
  V=1 ; false )
- export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/depends/$HOST/lib
- if [ "$RUN_TESTS" = "true" ]; then travis_wait 30 make $MAKEJOBS check VERBOSE=1;
  fi
- if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then extended="--extended --exclude pruning,dbcrash";
  fi
- if [ "$RUN_TESTS" = "true" ]; then test/functional/test_runner.py --coverage --quiet
  ${extended}; fi
- if [ "$HOST" = "x86_64-apple-darwin11" ]; then
    cd $TRAVIS_BUILD_DIR/build/ && tar -zcvf "Garlicoin-${HOST}.tar.gz" garlicoin-x86_64-apple-darwin11/dist/;
  else
    cd $TRAVIS_BUILD_DIR/out/$TRAVIS_PULL_REQUEST && tar -zcvf "Garlicoin-${HOST}.tar.gz" *$HOST;
  fi
after_script:
- echo $TRAVIS_COMMIT_RANGE
- echo $TRAVIS_COMMIT_LOG
before_deploy:
- git tag "$(date +'%Y%m%d%H%M%S')-${HOST}"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: uuIrcVR8fmTpexs8T8Qjmuc0/F1Yi9NUf4R1np/lZz4PF9zmT4KsIieTyKMYSwe8ogWoKvm1oaYlyoCO1rn3EkoBvOc178fUZnnhmxnZFCIMkWOf6ZL69MmLBUB0ZiIzvrjs611iunrxej3/R95BgnSie6BMQzQV30B23gAEKvs5x5TB53gPELhkH/1CWYSqK0XBoM354SXzzVR1o5fRZlRjyhbnrwAuuqbDM2+Ti5Cudxf1+36ynPrM8GfCqdfDn0+AJNua9eCuAoXQRBIdi9MGxubWVo1Y35/IERMlsTjZMj11QWpClPizio9r7TcJttQ/YzJu09OewPo+MkqNc5GCSn71xzQft1eiVU0Ch5dSyOuD83l9vs/Uc1hZbl8fovmEnjWGG/3yKX6BsQxYwavP5zEaizmfoduebwv5RV+abHNvw7Y6kw2DWM1WBi2e2NQsv3A6kCxSdEhRrLBBV77Wszd4Br9qwsraVzB2m6lIlQCWXgnyAv97AWdVHiIbNyEEJ/61mXN1lAImnCHurX4DC5RlSsFCUpWb7jXLgt9gthqZ5xhFjzrW5AIWO0BWw6lPAt59OUN2WFm2u/BTqw+A9eQwxmsLhxJ6RzRg8Cb05TMMXjON+Ix2TG0VgGwQ0U2eLAMN41lT/93Ey3k3BysMmK8ayJn3pWdJBeP0maw=
  file: "Garlicoin-${HOST}.tar.gz"
  on:
    repo: GarlicoinOrg/Garlicoin
